export const zonedata = {
  narayanganjzone: [
    "tongibari",
    "zinzira",
    "sonargaon",
    "bandar",
    "nitaiganj",
    "abdullahpur",
    "narayanganjsadar",
    "kashipur",
    "modonpur",
    "rikabibazar",
    "chunkutia",
    "munshiganj",
    "alinagar",
    "hasnabad",
    "baluchar",
    "sirajdikhan",
  ],
};
