import localFont from "next/font/local";
import NavBar from "../_componrnt/nav/NavBar";
import "../globals.css";
import NavBarLeft from "./_component/NavBarLeft";
import { auth } from "@/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar />
        <div className="grid grid-cols-12">
          <div className="col-span-12 xl:col-span-2  p-2">
            <NavBarLeft />
          </div>
          <div className="col-span-12 xl:col-span-10 p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
